FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install mlflow==2.9.0 psycopg2-binary boto3

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db"]
